//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENTITYFRAMEWORKDBEntities : DbContext
    {
        public ENTITYFRAMEWORKDBEntities()
            : base("name=ENTITYFRAMEWORKDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAboutt> TBLAboutt { get; set; }
        public virtual DbSet<TBLContact> TBLContact { get; set; }
        public virtual DbSet<TBLPerson> TBLPerson { get; set; }
    }
}
