//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAboutt
    {
        public int Aid { get; set; }
        public int Pid { get; set; }
        public string EgitimDerecesi { get; set; }
        public string Mezuniyet { get; set; }
        public string DogumYeri { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public int Yas { get; set; }
    
        public virtual TBLPerson TBLPerson { get; set; }
    }
}
