//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLContact
    {
        public int Cid { get; set; }
        public int Pid { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
    
        public virtual TBLPerson TBLPerson { get; set; }
    }
}
